version: '3'
services:
  swarmer:
    container_name: swarmer
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
      - redis
    environment:
      - DEBUG=server
      - NODE_ENV=development
      - MONGO_DB_URI=mongodb://mongodb:27017/swarmer_dock
      - PORT=3000
      - REDIS_DB_HOST=redis
      - REDIS_DB_PORT=6379
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379