version: '3'
services:
  swarmer:
    image: powerandlight/swarmer:firstrun
    environment:
      - DEBUG=swarmer
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "3000:3000"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
      image: redis
      ports:
        - "6379:6379"
      volumes:
        - "/home/docker/data:/data"
      deploy:
        placement:
          constraints: [node.role == manager]
      command: redis-server --appendonly yes
      networks:
        - webnet
networks:
  webnet: